// All UI strings in Greek — centralised for future i18n
export const strings = {
  // Navigation
  nav: {
    home: 'Αρχική',
    search: 'Αναζήτηση',
    login: 'Σύνδεση',
    register: 'Εγγραφή',
    account: 'Λογαριασμός',
    logout: 'Αποσύνδεση',
    favorites: 'Αγαπημένα',
    reservations: 'Κρατήσεις μου',
  },

  // Hero / Home
  home: {
    heroTitle: 'Ανακαλύψτε τον καλύτερο χώρο για εσάς',
    heroSubtitle: 'Κάντε κράτηση σε beach clubs, pool bars, rooftops και εστιατόρια',
    searchPlaceholder: 'Αναζητήστε χώρο, πόλη ή κατηγορία…',
    featuredTitle: 'Προτεινόμενοι Χώροι',
    categoriesTitle: 'Κατηγορίες',
    statsShops: 'Καταστήματα',
    statsReservations: 'Κρατήσεις',
    ctaExplore: 'Εξερευνήστε',
    ctaBook: 'Κάντε Κράτηση',
    ctaViewAll: 'Δείτε Όλα',
  },

  // Search page
  search: {
    title: 'Αποτελέσματα Αναζήτησης',
    filters: 'Φίλτρα',
    sortBy: 'Ταξινόμηση',
    sortRelevance: 'Σχετικότητα',
    sortRating: 'Βαθμολογία',
    sortName: 'Αλφαβητικά',
    sortPriceLow: 'Τιμή (Χαμηλή → Υψηλή)',
    sortPriceHigh: 'Τιμή (Υψηλή → Χαμηλή)',
    city: 'Πόλη',
    category: 'Κατηγορία',
    date: 'Ημερομηνία',
    time: 'Ώρα',
    partySize: 'Άτομα',
    allCities: 'Όλες οι πόλεις',
    allCategories: 'Όλες οι κατηγορίες',
    noResults: 'Δεν βρέθηκαν αποτελέσματα',
    noResultsHint: 'Δοκιμάστε να αλλάξετε τα φίλτρα αναζήτησης ή',
    noResultsLink: 'δείτε όλους τους χώρους',
    results: (n: number) => `${n} χώροι βρέθηκαν`,
    loadMore: 'Φόρτωση περισσότερων',
    page: (c: number, t: number) => `Σελίδα ${c} από ${t}`,
  },

  // City page
  city: {
    shopsIn: (name: string) => `Χώροι στη ${name}`,
    noShops: 'Δεν υπάρχουν καταχωρήσεις σε αυτή την πόλη ακόμα.',
    noShopsAction: 'Αναζητήστε σε άλλη πόλη',
    noShopsSearch: 'ή χρησιμοποιήστε γενική αναζήτηση',
  },

  // Venue detail
  venue: {
    bookNow: 'Κάντε Κράτηση',
    newVenue: 'Νέος Χώρος',
    noRating: 'Χωρίς βαθμολογία',
    reviews: (n: number) => n === 1 ? '1 κριτική' : `${n} κριτικές`,
    openingHours: 'Ωράρια',
    description: 'Περιγραφή',
    location: 'Τοποθεσία',
    contact: 'Επικοινωνία',
    social: 'Κοινωνικά Δίκτυα',
    policy: 'Πολιτική Κρατήσεων',
    noReviews: 'Δεν υπάρχουν κριτικές ακόμα.',
    writeReview: 'Γράψτε Κριτική',
    addToFavorites: 'Προσθήκη στα Αγαπημένα',
    removeFromFavorites: 'Αφαίρεση από Αγαπημένα',
    days: {
      monday: 'Δευτέρα',
      tuesday: 'Τρίτη',
      wednesday: 'Τετάρτη',
      thursday: 'Πέμπτη',
      friday: 'Παρασκευή',
      saturday: 'Σάββατο',
      sunday: 'Κυριακή',
    },
    closed: 'Κλειστό',
    open: 'Ανοιχτό',
    fullyBooked: 'Πλήρης για αυτή την ημερομηνία',
  },

  // Booking flow
  booking: {
    title: 'Κράτηση',
    stepDate: 'Επιλογή ημερομηνίας & ώρας',
    stepDetails: 'Στοιχεία κράτησης',
    stepConfirm: 'Επιβεβαίωση',
    date: 'Ημερομηνία',
    time: 'Ώρα',
    seats: 'Άτομα',
    name: 'Όνομα',
    surname: 'Επώνυμο',
    email: 'Email',
    phone: 'Τηλέφωνο',
    comment: 'Σχόλια (προαιρετικά)',
    commentPlaceholder: 'Ειδικές απαιτήσεις, αλλεργίες…',
    next: 'Επόμενο',
    back: 'Πίσω',
    confirm: 'Επιβεβαίωση Κράτησης',
    success: 'Η κράτησή σας καταχωρήθηκε!',
    successHint: 'Θα λάβετε email επιβεβαίωσης σύντομα.',
    error: 'Κάτι πήγε στραβά. Παρακαλώ δοκιμάστε ξανά.',
    loginRequired: 'Συνδεθείτε ή συνεχίστε ως επισκέπτης',
    guestContinue: 'Συνέχεια ως Επισκέπτης',
    loginContinue: 'Σύνδεση',
    selectTime: 'Επιλέξτε ώρα',
    noSlots: 'Δεν υπάρχουν διαθέσιμα χρονοδιαστήματα για αυτή την ημερομηνία.',
    persons: (n: number) => n === 1 ? '1 άτομο' : `${n} άτομα`,
  },

  // Auth
  auth: {
    loginTitle: 'Σύνδεση',
    registerTitle: 'Εγγραφή',
    email: 'Email',
    password: 'Κωδικός',
    name: 'Όνομα',
    surname: 'Επώνυμο',
    phone: 'Τηλέφωνο',
    loginBtn: 'Σύνδεση',
    registerBtn: 'Εγγραφή',
    googleBtn: 'Συνέχεια με Google',
    haveAccount: 'Έχετε ήδη λογαριασμό;',
    noAccount: 'Δεν έχετε λογαριασμό;',
    forgotPassword: 'Ξεχάσατε τον κωδικό;',
    resetPassword: 'Επαναφορά Κωδικού',
    resetSent: 'Στάλθηκε email επαναφοράς.',
  },

  // Account
  account: {
    title: 'Ο Λογαριασμός μου',
    profile: 'Προφίλ',
    reservations: 'Κρατήσεις',
    favorites: 'Αγαπημένα',
    editProfile: 'Επεξεργασία',
    save: 'Αποθήκευση',
    cancel: 'Ακύρωση',
    noReservations: 'Δεν έχετε κρατήσεις ακόμα.',
    noFavorites: 'Δεν έχετε αγαπημένα ακόμα.',
    reservationStatus: {
      pending: 'Σε αναμονή',
      accepted: 'Αποδεκτή',
      rejected: 'Απορρίφθηκε',
      notShown: 'Δεν εμφανίστηκε',
      noshow: 'Δεν εμφανίστηκε',
      completed: 'Ολοκληρώθηκε',
      cancelled: 'Ακυρώθηκε',
    },
    cancelReservation: 'Ακύρωση Κράτησης',
  },

  // Common
  common: {
    loading: 'Φόρτωση…',
    error: 'Σφάλμα',
    retry: 'Δοκιμάστε ξανά',
    close: 'Κλείσιμο',
    seeMore: 'Δείτε περισσότερα',
    backToHome: 'Επιστροφή στην Αρχική',
    notFound: 'Η σελίδα δεν βρέθηκε',
    notFoundHint: 'Ο σύνδεσμος που ακολουθήσατε δεν υπάρχει.',
  },
} as const;
